// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4zigDDRPnYyxEx7vrE5KKk-YCkKo67Xc',
    appId: '1:117994239781:web:381f3f74cd7d8d77094ccc',
    messagingSenderId: '117994239781',
    projectId: 'echo-56e8f',
    authDomain: 'echo-56e8f.firebaseapp.com',
    storageBucket: 'echo-56e8f.appspot.com',
    measurementId: 'G-JMNL37PT8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0WsmY8eRRYgr-N6Ir5T_PmB6wHibJ66k',
    appId: '1:117994239781:android:1499438b4404676e094ccc',
    messagingSenderId: '117994239781',
    projectId: 'echo-56e8f',
    storageBucket: 'echo-56e8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKRPVHtbvoUyl_ZLgzOh6_8Nk0EWLIfyw',
    appId: '1:117994239781:ios:f63929f30c3ed25c094ccc',
    messagingSenderId: '117994239781',
    projectId: 'echo-56e8f',
    storageBucket: 'echo-56e8f.appspot.com',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKRPVHtbvoUyl_ZLgzOh6_8Nk0EWLIfyw',
    appId: '1:117994239781:ios:e48f1f23f7e33a5a094ccc',
    messagingSenderId: '117994239781',
    projectId: 'echo-56e8f',
    storageBucket: 'echo-56e8f.appspot.com',
    iosBundleId: 'com.example.echo.RunnerTests',
  );
}
